deepeth/mars

- src/exporters/blocks.rs
- src/exporters/receipts.rs
> refactor: cleanup unwraps

- .github/workflows/rust.yml
> chore: add ci

- src/tracings/tracer.rs
- src/workers/receipts.rs
> chore: remove chunks executor for receipts worker and slient the jaeger

- .gitignore
- bin/mars.rs
- src/configs/config.rs
- src/exceptions/exception_into.rs
- tests/it/common.rs
Add exporter output directory
Close #issue
> chore: add output_dir

- bin/mars.rs
- src/exporters/blocks.rs
- src/exporters/receipts.rs
- src/workers/blocks.rs
- src/workers/mod.rs
- src/workers/receipts.rs
> chore: add worker

- .gitignore
- Cargo.lock
- Cargo.toml
- src/contexts/context.rs
- src/exceptions/exception_into.rs
- src/exporters/blocks.rs
* Export to CSV file
Close #issue
> feat: support export to csv

- Cargo.lock
- Cargo.toml
- common/formats/Cargo.toml
- common/formats/src/csv.rs
- common/formats/src/lib.rs
- ethetl/Cargo.toml
- ethetl/src/exporters/blocks.rs
> chore: add format for csv/parquet file

- ethetl/src/configs/config.rs
- ethetl/src/eth/blocks.rs
- ethetl/src/eth/receipts.rs
- ethetl/src/exporters/blocks.rs
Add block to csv file
Close #issue
> feat: add block to csv file

- ethetl/src/contexts/context.rs
- ethetl/src/exporters/blocks.rs
Export tx data to CSV file.
Close #11
> feat: add tx export

- ethetl/src/exporters/blocks.rs
- schemas/databend/blocks.sql
- schemas/databend/transactios.sql
add schema for databend:
* blocks
* transactions
Close #issue
> feat: add schema for databend

- common/formats/src/csv.rs
- ethetl/src/exporters/blocks.rs
Unify the API `write_csv(path: &str, schema: Schema, columns: Chunk<Box<dyn Array>>) -> Result<()> `
Close #issue
> feat: add schema and chunk to unify the write file api

- ethetl/bin/ethetl.rs
- ethetl/src/exporters/blocks.rs
- ethetl/src/exporters/mod.rs
- ethetl/src/exporters/receipts.rs
- ethetl/src/workers/blocks.rs
- ethetl/src/workers/receipts.rs
- ethetl/tests/it/exporters/blocks.rs
> Export receipt file

- ethetl/src/configs/config.rs
- ethetl/src/contexts/context.rs
- ethetl/src/eth/blocks.rs
- ethetl/src/eth/receipts.rs
- ethetl/src/exporters/worker.rs
- ethetl/tests/it/common.rs
* Fix worker scheduler
* Add web3_batch_size to config
Close #issue
> bug: fix worker scheduler

- Cargo.lock
- common/exceptions/Cargo.toml
- common/exceptions/src/lib.rs
- common/exceptions/src/retry.rs
- ethetl/src/eth/blocks.rs
- ethetl/src/eth/receipts.rs
- ethetl/src/exporters/pipeline.rs
- ethetl/src/exporters/worker.rs
Add retry for web3 api fetch
Close #35
> feat: add retry for web3 api fetch

- schemas/databend/blocks.sql
- schemas/databend/receipts.sql
- schemas/databend/transactios.sql
Schema: BIGINT -> BIGINT UNSIGNED
Close #issue
> fix: BIGINT -> BIGINT UNSIGNED

- README.md
- ethetl/bin/ethetl.rs
- ethetl/src/configs/config.rs
- ethetl/src/exporters/blocks.rs
- ethetl/src/exporters/mod.rs
- ethetl/src/exporters/pipeline.rs
- ethetl/src/exporters/receipts.rs
Add receipt exporter to pipeline
Close #issue
> feat: export receipts

- Cargo.lock
- Cargo.toml
- Makefile
- common/configs/Cargo.toml
- common/configs/src/eth.rs
- common/configs/src/lib.rs
- common/configs/src/log.rs
- common/configs/src/storage.rs
- common/exceptions/Cargo.toml
- common/exceptions/src/exception_into.rs
- ethetl/Cargo.toml
- ethetl/bin/ethetl.rs
- ethetl/src/contexts/context.rs
- ethetl/tests/it/common.rs
- ethetl/tests/it/exporters/blocks.rs
- ethetl/tests/it/exporters/receipts.rs
- ethetl/tests/it/fetchers/blocks.rs
- ethetl/tests/it/fetchers/receipts.rs
- scripts/deploy/ethetl_config_spec.toml
Add common/configs
Close #issue
> feat: add common/configs

- .gitignore
- common/configs/src/eth.rs
- common/configs/src/log.rs
- common/configs/src/storage.rs
- ethetl/src/exporters/pipeline.rs
- scripts/deploy/ethetl_config_spec.toml
> bug: fix config load

- ethetl/src/exporters/mod.rs
- ethetl/src/exporters/receipts.rs
- ethetl/src/exporters/token_transfer.rs
- schemas/databend/token_transfer.sql
Add token transfer
Close #issue
> feat: add token transfer

- ethetl/src/eth/blocks.rs
- ethetl/src/eth/receipts.rs
- ethetl/src/exporters/pipeline.rs
- ethetl/src/exporters/worker.rs
> feat: Add failure remove to pipeline

- common/exceptions/src/exception_code.rs
- ethetl/src/contexts/progress.rs
- ethetl/src/eth/blocks.rs
- ethetl/src/eth/contracts.rs
- ethetl/src/eth/mod.rs
> Add contracts web3 api

- ethetl/src/exporters/token_transfers.rs
> fix token extract

- ethetl/src/exporters/receipts.rs
- ethetl/src/exporters/token_transfers.rs
- schemas/databend/logs.sql
- schemas/databend/receipts.sql
> chore: fix parquet import

- .github/workflows/dev.yml
- .github/workflows/release.yml
- Cross.toml
- docker/cross/Dockerfile.aarch64-unknown-linux-gnu
- docker/cross/Dockerfile.x86_64-unknown-linux-gnu
> ci: link openssl static

- ethetl/src/contexts/progress.rs
- ethetl/src/exporters/logs.rs
- ethetl/src/exporters/token_transfers.rs
- ethetl/src/exporters/worker.rs
> Add progress to logs and token_transfers

- common/configs/src/eth.rs
> feat: reduce the default batch size

- .github/workflows/release.yml
- .gitignore
- docker/Dockerfile
> ci: release docker image to ghcr.io

- ethetl/src/exporters/transactions.rs
- schemas/databend/transactios.sql
> feat: Change value from string to double

- Cargo.lock
- common/configs/src/lib.rs
- common/eth/Cargo.toml
- common/eth/src/lib.rs
- common/exceptions/Cargo.toml
- common/exceptions/src/lib.rs
- common/storages/Cargo.toml
- common/storages/src/lib.rs
- common/tracings/Cargo.toml
- common/tracings/src/lib.rs
- ethetl/Cargo.toml
- ethetl/src/lib.rs
> Shrink the deps

- common/eth/src/abi.rs
- common/eth/src/encode.rs
- common/eth/tests/it/encode.rs
- ethetl/src/exporters/blocks.rs
- ethetl/src/exporters/logs.rs
- ethetl/src/exporters/receipts.rs
- ethetl/src/exporters/token_transfers.rs
- ethetl/src/exporters/transactions.rs
Add more hex functions to instead of format.
Close #issue
> Add more hex functions

- common/configs/src/lib.rs
- common/configs/src/storage.rs
- common/storages/src/lib.rs
- common/storages/src/storage.rs
- ethetl/src/contexts/context.rs
> feat: remove write s3 directly

- common/configs/src/eth.rs
Set parquet as the default format
Close #issue
> chore: change parquet as default format

- schemas/databend/2_example.sql
Signed-off-by: grapebaba <281165273@qq.com>
fix databend latest 6 hours NFT bug
Close #80
> bug:fix databend latest 6 hours NFT bug

- common/configs/src/eth.rs
- ethetl/bin/ethetl_stream.rs
- ethetl/src/contexts/progress.rs
- ethetl/src/eth/blocks.rs
- ethetl/src/stream/stream.rs
> feat: add latest block to progress

- schemas/databend/2_ingest.sql
- schemas/databend/README.md
- scripts/deploy/ethetl_config_spec.toml
> feat: add how to ingest data from external stage

- Cargo.lock
- common/configs/Cargo.toml
- common/configs/src/storage.rs
- scripts/deploy/ethetl_config_spec.toml
> chore: bump serfig and clap to latest

- Cargo.lock
- common/configs/Cargo.toml
- common/configs/src/eth.rs
- common/configs/src/log.rs
- common/configs/src/storage.rs
- common/configs/tests/it/config.rs
- common/configs/tests/it/main.rs
- scripts/deploy/ethetl_config_spec.toml
> chore: fix config same as default

- common/configs/src/eth.rs
> chore: small the batch_size from 10000 to 1000

- schemas/databend/1_schema.sql
- schemas/databend/README.md
> fix: fix token transfer value schema
